<a href="https://colab.research.google.com/github/mani2222278/Rebounce-Applied-AI-and-Analytics-code/blob/main/Copy_of_Q2_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 4 Practice — NumPy Basics
**Python for Data Analytics Bootcamp**

Solve each exercise in the code cell below it. Check your work against the matching Solutions notebook when done.

---

### Exercise 1 — A 1D array from a list

Import NumPy using its standard alias. Then create a one-dimensional NumPy array from the list `[12, 25, 37, 48, 56]` and print it.

In [ ]:
import numpy as np

arr = np.array([12, 25, 37, 48, 56])
print(arr)

[12 25 37 48 56]


### Exercise 2 — A 2D array from a list of lists

Create a two-dimensional NumPy array with 3 rows and 2 columns from the values below, and print it:

```
[[1, 2],
 [3, 4],
 [5, 6]]
```

In [ ]:
# Write your code here
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


---

### Exercise 3 — An array of zeros

Use the appropriate NumPy function to create an array of zeros with shape `(2, 4)`. Print the result.

In [ ]:
# Write your code here
arr = np.zeros((2, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


---

### Exercise 4 — An array of ones

Create an array of ones with shape `(3, 3)` and an integer data type. Print it.

In [ ]:
# Write your code here
arr = np.ones((3, 3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


---

### Exercise 5 — Generate a range with arange()

Use `arange()` to create an array of all even numbers from 0 up to (but not including) 20, then print it.

Expected output:
```
[ 0  2  4  6  8 10 12 14 16 18]
```

In [ ]:
# Write your code here
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


---

### Exercise 6 — Reshape a 1D array into 2D

Create a 1D array of the numbers 1 through 12 using `arange()`, then reshape it into a 2D array with 3 rows and 4 columns. Print the reshaped array.

In [ ]:
# Write your code here
arr = np.arange(1, 13)
arr = arr.reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


---

### Exercise 7 — Inspect an array's properties

Given the array below, print its shape, data type (`dtype`), total number of elements (`size`), and number of dimensions (`ndim`):

```python
data = np.array([[10, 20, 30],
                 [40, 50, 60]])
```

In [ ]:
# Write your code here
data = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("Shape:", data.shape)
print("Dtype:", data.dtype)
print("Size:", data.size)
print("Dimensions:", data.ndim)

Shape: (2, 3)
Dtype: int64
Size: 6
Dimensions: 2


---

### Exercise 8 — Add and subtract arrays element-wise

Create two arrays, `prices = [100, 250, 400]` and `discounts = [10, 25, 50]`. Print the element-wise sum of the two arrays, and the result of subtracting `discounts` from `prices`.

In [ ]:
# Write your code here
prices = np.array([100, 250, 400])
discounts = np.array([10, 25, 50])

print("Sum:", prices + discounts)
print("After discount:", prices - discounts)

Sum: [110 275 450]
After discount: [ 90 225 350]


---

### Exercise 9 — Multiply arrays and scale by a number

Create an array `quantities = [2, 5, 3]` and an array `unit_prices = [50, 20, 100]`. Print the element-wise product (the total cost per item). Then print the result of multiplying `quantities` by the scalar `10`.

In [ ]:
# Write your code here
quantities = np.array([2, 5, 3])
unit_prices = np.array([50, 20, 100])

print("Total cost:", quantities * unit_prices)
print("Quantities × 10:", quantities * 10)

Total cost: [100 100 300]
Quantities × 10: [20 50 30]


---

### Exercise 10 — Build and reshape in one step

Create an array of the numbers 1 through 15 using `arange()`, reshape it into 5 rows and 3 columns, then print both the reshaped array and its shape.

In [ ]:
# Write your code here
arr = np.arange(1, 16).reshape(5, 3)

print(arr)
print("Shape:", arr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Shape: (5, 3)


---

### Exercise 11 — Combine what you've learned

Bring several tools together. Use `arange()` to build two arrays: `a` holding the numbers 0 to 5, and `b` holding the numbers 10 to 15. Reshape each into a 2×3 array, then print their element-wise sum.

In [ ]:
# Write your code here
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(10, 16).reshape(2, 3)

print(a + b)

[[10 12 14]
 [16 18 20]]
